services:
  walkys-app:
    container_name: walkys-app
    hostname: walkys-app
    build:
      context: ./app
      dockerfile: Dockerfile
      network: host
      args:
        VITE_API_ENDPOINT: ${PUBLIC_POCKETBASE_URL:-http://localhost:8090}
        VITE_PUBLIC_POCKETBASE_URL: ${PUBLIC_POCKETBASE_URL:-http://localhost:8090}
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      NODE_ENV: "production"
      POCKETBASE_URL: "http://walkys-api:8090"
      PUBLIC_POCKETBASE_URL: ${PUBLIC_POCKETBASE_URL:-http://localhost:8090}
      PUBLIC_APP_URL: ${PUBLIC_APP_URL:-https://walkys.com}
      API_PB_ADMIN_EMAIL: ${API_PB_ADMIN_EMAIL:-}
      API_PB_ADMIN_PASSWORD: ${API_PB_ADMIN_PASSWORD:-}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-465}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASS: ${SMTP_PASS:-}
      EMAIL_FROM: ${EMAIL_FROM:-}
      ANTI_BOT_SECRET: ${ANTI_BOT_SECRET:-}
    networks:
      - walkys

  walkys-api:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: walkys-api
    hostname: walkys-api
    restart: unless-stopped
    volumes:
      - ./api:/api
      - ./api/data:/pb_data
    networks:
      - walkys
    ports:
      - "8090:8090"

networks:
  walkys:
    external: true
