services:
  walkys-app:
    container_name: walkys-app
    hostname: walkys-app
    build:
      context: ./app
      dockerfile: Dockerfile
      network: host
      args:
        VITE_API_ENDPOINT: ${PUBLIC_POCKETBASE_URL:-http://localhost:8090}
        VITE_PUBLIC_POCKETBASE_URL: ${PUBLIC_POCKETBASE_URL:-http://localhost:8090}
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      NODE_ENV: "production"
      POCKETBASE_URL: "http://walkys-api:8090"
      PUBLIC_POCKETBASE_URL: ${PUBLIC_POCKETBASE_URL:-http://localhost:8090}
    networks:
      - walkys

  walkys-api:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: walkys-api
    hostname: walkys-api
    restart: unless-stopped
    volumes:
      - ./api:/api
      - ./api/data:/pb_data
    networks:
      - walkys
    ports:
      - "8090:8090"

networks:
  walkys:
    external: true
