import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("auth/:mode", "routes/auth.$mode.tsx"),
  route("collection/:collection", "routes/collection.$collection.tsx"),
  route("category/:category", "routes/category.$category.tsx"),
  route("product/:product", "routes/product.$product.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password/:token", "routes/reset-password.$token.tsx"),
  route("dashboard", "routes/dashboard.tsx"),
  route("pending-approval", "routes/pending-approval.tsx"),
  route("blocked", "routes/blocked.tsx"),
  route("registration-success", "routes/registration-success.tsx"),
  route("backoffice", "routes/backoffice.tsx", [
    index("routes/backoffice.index.tsx"),
    route("pages/:page", "routes/backoffice.pages.$page.tsx"),
    route("products", "routes/backoffice.products.tsx"),
    route("products/:id", "routes/backoffice.products.$id.tsx"),
    route("categories", "routes/backoffice.categories.tsx"),
    route("categories/:id", "routes/backoffice.categories.$id.tsx"),
    route("collections", "routes/backoffice.collections.tsx"),
    route("collections/:id", "routes/backoffice.collections.$id.tsx"),
    route("contact-replies", "routes/backoffice.contact-replies.tsx"),
    route("contact-replies/:id", "routes/backoffice.contact-replies.$id.tsx"),
    route("users", "routes/backoffice.users.tsx"),
    route("users/:id", "routes/backoffice.users.$id.tsx"),
    route("orders", "routes/backoffice.orders.tsx"),
    route("orders/:id", "routes/backoffice.orders.$id.tsx"),
    route("translations", "routes/backoffice.translations.tsx"),
    route("layout", "routes/backoffice.layout.tsx"),
  ]),
  route("about", "routes/about.tsx"),
  route("terms", "routes/terms.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("contact", "routes/contact.tsx"),
  route("checkout", "routes/checkout.tsx"),
  route("logout", "routes/logout.tsx"),
  route("orders", "routes/orders.tsx"),
] satisfies RouteConfig;
